# Generated by Django 4.2.19 on 2025-02-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('destination_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('source_port', models.PositiveIntegerField(blank=True, null=True)),
                ('destination_port', models.PositiveIntegerField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, max_length=20, null=True)),
                ('action', models.CharField(blank=True, max_length=50, null=True)),
                ('bytes_sent', models.BigIntegerField(blank=True, null=True)),
                ('bytes_received', models.BigIntegerField(blank=True, null=True)),
                ('packets_sent', models.BigIntegerField(blank=True, null=True)),
                ('packets_received', models.BigIntegerField(blank=True, null=True)),
                ('sent_pkt', models.BigIntegerField(blank=True, null=True)),
                ('rcvd_pkt', models.BigIntegerField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('application', models.CharField(blank=True, max_length=100, null=True)),
                ('app_category', models.CharField(blank=True, max_length=100, null=True)),
                ('app_subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('severity', models.CharField(blank=True, max_length=20, null=True)),
                ('firewall_name', models.CharField(blank=True, max_length=100, null=True)),
                ('rule_name', models.CharField(blank=True, max_length=100, null=True)),
                ('policy_id', models.IntegerField(blank=True, null=True)),
                ('policy_uuid', models.CharField(blank=True, max_length=100, null=True)),
                ('interface_in', models.CharField(blank=True, max_length=100, null=True)),
                ('interface_out', models.CharField(blank=True, max_length=100, null=True)),
                ('country_source', models.CharField(blank=True, max_length=100, null=True)),
                ('country_destination', models.CharField(blank=True, max_length=100, null=True)),
                ('nat_source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('nat_destination_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('nat_source_port', models.PositiveIntegerField(blank=True, null=True)),
                ('nat_destination_port', models.PositiveIntegerField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('threat_name', models.CharField(blank=True, max_length=255, null=True)),
                ('threat_id', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('src_zone', models.CharField(blank=True, max_length=100, null=True)),
                ('dst_zone', models.CharField(blank=True, max_length=100, null=True)),
                ('src_interface', models.CharField(blank=True, max_length=100, null=True)),
                ('dst_interface', models.CharField(blank=True, max_length=100, null=True)),
                ('misc_field1', models.TextField(blank=True, null=True)),
                ('misc_field2', models.TextField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='logs_traffi_timesta_c8a0e7_idx'), models.Index(fields=['source_ip'], name='logs_traffi_source__c3bf1e_idx'), models.Index(fields=['destination_ip'], name='logs_traffi_destina_960fdf_idx'), models.Index(fields=['session_id'], name='logs_traffi_session_aa3053_idx')],
            },
        ),
    ]
