# Generated by Django 4.2.19 on 2025-02-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_trafficlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficlog',
            name='date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trafficlog',
            name='time',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
